codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "50...75"

  status:
    # Disable patch since it is noisy and not correct
    patch:
      default:
        enabled: no
        if_not_found: success

comment: false