apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: object-store
spec:
  type: bindings.localstorage
  version: v1
  metadata:
    - name: rootPath
      value: "./resources/storage"
    - name: direction
      value: "output"