name: Test & Publish Coverage

on:
  push:
    branches:
      - master
jobs:
  func-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - run: go mod tidy
      - name: Execute tests
        run: go test ./...  -covermode=atomic -coverprofile=coverage.out
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          verbose: true