name: Test & Publish Coverage

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'resources/**'
jobs:
  func-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18.0'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev pulseaudio alsa-utils dbus-x11 ffmpeg
          pulseaudio -D
      - run: go mod tidy
      - name: Install Dapr CLI
        uses: dapr/setup-dapr@v1
        with:
          version: '1.11.0'
      - name: Initialize Dapr
        shell: bash
        run: |
          dapr uninstall 
          dapr init
          dapr --version
      - name: Execute tests
        run: make test_with_dapr
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          verbose: true